### ISSUE TITLE
missing $MAGScoT_folder/example

### ISSUE THREAD

**Issue by chrisgulvik** [ikmb/MAGScoT#2]
Thanks for including the HMM files, it makes it much simpler to get the software up and running.

It looks like example commands use `cd $MAGScoT_folder/example` with files inside for testing. Could you upload that subdir in this repo to be able to follow the example as listed in the README? Exact example cmds with expected output shown would be valuable in confirming the software is behaving as-expected in my environment.

**Comment by mruehlemann** [comment]
thank you for your note, I forgot to upload the example files - now they are where they are supposed to be.

I'll try to add a more comprehensive "tutorial" with the example data soon.
