### ISSUE TITLE
MAGScoT give a bad MAG refinement result

### ISSUE THREAD

**Issue by quliping** [ikmb/MAGScoT#5]
Hello, MAGScoT is an interesting software and is helpful for my metageome analysis. However, the refinement result of MAGScoT seems not good? I tried to analysis a sample using metaWrap and MAGScoT. I have three bin sets which were produced by maxbin2, metabat2, and vamb. Both MAGScoT (default parameters) and metaWRAP (bin_refinement module, completeness threshold 50% and contamination threshold 10%) produced five final MAGs, but results from MAGScoT seems have fewer species and very high contamination? Indeed MAGScoT takes less time and it's MAGs have higher completeness than metaWRAP, but such high contamination MAGs seems could not be used in article.

**metaWRAP:**
![image](https://github.com/ikmb/MAGScoT/assets/39583607/14602b08-95b5-46b5-9e5d-98c1e80772c5)

**MAGScoT:**
![image](https://github.com/ikmb/MAGScoT/assets/39583607/cbb3e7ee-7025-41a9-b545-ce715620a9db)

**Comment by mruehlemann** [comment]
Hi! 
Thank you for using MAGScoT. It looks like in this particular case of low numbers and high incompleteness of assembled genomes, the default scoring values in MAGScoT might not be perfectly fitting 

MAGScoT uses three scoring parameters as described in the published article:

![image](https://github.com/ikmb/MAGScoT/assets/5998663/d80ccfba-bca2-4367-ba71-4a21f636d3aa)

These parameters can be changed:

`

	-a SCORE_A, --score_a=SCORE_A
		Scoring parameter a [default=1]

	-b SCORE_B, --score_b=SCORE_B
		Scoring parameter b [default=0.5]

	-c SCORE_C, --score_c=SCORE_C
		Scoring parameter c [default=0.5]

`
metaWRAP has a much higher weight on duplicated SCG (b=5) (and lower weight on the multi SCG, c=0) if I remember correctly. Maybe you can try those values for MAGScoT and see if this improves your outcomes.

Best wishes,
Malte

**Comment by yuqing-feng** [comment]
@mruehlemann 

> It looks like in this particular case of low numbers and high incompleteness of assembled genomes, the default scoring values in MAGScoT might not be perfectly fitting.

Is it a good practice to filt out low quality MAGs (i.e. completeness < 50%) before running MAGScoT?

**Comment by mruehlemann** [comment]
by default, MAGScoT only retains MAGs with a score > 0.5 which can be adjusted using the `-t THRESHOLD` or `--threshold=THRESHOLD` option which - with default values or any value which keeps the `-a` parameter at 1 - will not retain any MAG with completeness < 50% as these will never reach a value above 0.5
